export enum ActionTypes {
LOGGED_IN_USER = "LOGGED_IN_USER",
SIGN_UP_USER = "SIGN_IN_USER",
LOG_OUT_USER = "LOG_OUT_USER",
SET_ALL_PRODUCTS="SET_ALL_PRODUCTS",
ADD_TO_CART="ADD_TO_CART",
DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART",
ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART",
EMPTY_BASKET = "EMPTY_BASKET",
SET_MY_ORDERS = "SET_MY_ORDERS",
SET_LIKE = "SET_LIKE",
CHECK_STOCK = "CHECK_STOCK"
}